import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import ReduxProvider from "./store/ReduxProvider";
import QueryProvider from "./QueryProvider";

export const metadata: Metadata = {
  title: "Brainsnack App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <QueryProvider>
            <main>
              <Toaster />
              {children}
            </main>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
